# Generated by Django 6.0.3 on 2026-04-08 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.CharField(max_length=20)),
                ('generated_time', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_reports', to='reports.uploadedreport')),
            ],
        ),
    ]
