# Generated by Django 6.0.3 on 2026-04-08 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_parsedreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='reports.parsedreport')),
            ],
        ),
    ]
