# Generated by Django 6.0.3 on 2026-04-09 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_customersection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est', models.CharField(blank=True, max_length=10)),
                ('pedido', models.CharField(blank=True, max_length=20)),
                ('seq', models.CharField(blank=True, max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('espess', models.CharField(blank=True, max_length=20)),
                ('larg', models.CharField(blank=True, max_length=20)),
                ('compr', models.CharField(blank=True, max_length=20)),
                ('ord_prod', models.CharField(blank=True, max_length=20)),
                ('sit_ordem', models.CharField(blank=True, max_length=50)),
                ('dt_entr', models.CharField(blank=True, max_length=20)),
                ('aa', models.CharField(blank=True, max_length=10)),
                ('qt_ped', models.CharField(blank=True, max_length=20)),
                ('qt_pc', models.CharField(blank=True, max_length=20)),
                ('qt_prod', models.CharField(blank=True, max_length=20)),
                ('qt_fatur', models.CharField(blank=True, max_length=20)),
                ('sdo_estoq', models.CharField(blank=True, max_length=20)),
                ('sit', models.CharField(blank=True, max_length=20)),
                ('pre_liq', models.CharField(blank=True, max_length=20)),
                ('pf', models.CharField(blank=True, max_length=20)),
                ('vlr_peca', models.CharField(blank=True, max_length=20)),
                ('pag', models.CharField(blank=True, max_length=20)),
                ('transp', models.CharField(blank=True, max_length=100)),
                ('cr_pro', models.CharField(blank=True, max_length=20)),
                ('cr_fat', models.CharField(blank=True, max_length=20)),
                ('o_compra', models.CharField(blank=True, max_length=50)),
                ('item_cli', models.CharField(blank=True, max_length=50)),
                ('mnf', models.CharField(blank=True, max_length=50)),
                ('raw_line', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.customersection')),
            ],
        ),
    ]
