# Generated by Django 6.0.3 on 2026-04-09 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_parseditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_prod', models.CharField(blank=True, max_length=20)),
                ('sit_ordem', models.CharField(blank=True, max_length=50)),
                ('qt_prod', models.CharField(blank=True, max_length=20)),
                ('sit', models.CharField(blank=True, max_length=20)),
                ('raw_line', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuations', to='reports.parseditem')),
            ],
        ),
    ]
