# Generated by Django 6.0.3 on 2026-04-09 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_continuationrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ped', models.CharField(blank=True, max_length=20)),
                ('total_pc', models.CharField(blank=True, max_length=20)),
                ('total_prod', models.CharField(blank=True, max_length=20)),
                ('total_fatur', models.CharField(blank=True, max_length=20)),
                ('total_sdo', models.CharField(blank=True, max_length=20)),
                ('total_valor', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total', to='reports.customersection')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ped', models.CharField(blank=True, max_length=20)),
                ('total_pc', models.CharField(blank=True, max_length=20)),
                ('total_prod', models.CharField(blank=True, max_length=20)),
                ('total_fatur', models.CharField(blank=True, max_length=20)),
                ('total_sdo', models.CharField(blank=True, max_length=20)),
                ('total_valor', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total', to='reports.parsedreport')),
            ],
        ),
    ]
