# Generated by Django 6.0.3 on 2026-04-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_customertotal_reporttotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customertotal',
            old_name='total_pc',
            new_name='total_in_prod',
        ),
        migrations.RenameField(
            model_name='reporttotal',
            old_name='total_pc',
            new_name='total_in_prod',
        ),
        migrations.RemoveField(
            model_name='customertotal',
            name='total_prod',
        ),
        migrations.RemoveField(
            model_name='reporttotal',
            name='total_prod',
        ),
        migrations.AlterField(
            model_name='customertotal',
            name='total_valor',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='reporttotal',
            name='total_valor',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
